In [3]:
import numpy as np

# 假设你的文件路径是 '.t'
data = np.loadtxt('./data/pipe_shape_detection2/left/left_0001.txt',delimiter=',')
print(data.shape)  # 打印数据形状以确认其维度

(41681, 3)


In [1]:
import numpy as np

# 创建一个3x3x3的三维数组
array_3d = np.zeros((3, 3, 3))

# 打印数组
print(array_3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [3]:
import numpy as np

# 创建一个3x3x3的三维数组
array_3d = np.zeros((5, 3))

# 打印数组
print(array_3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
import open3d as o3d
import numpy as np
import os

ply_path = "./data/pipe_shape_detection2/left/left_0001.ply"  # 将此路径替换为你的文件夹路径
point_cloud = o3d.io.read_point_cloud(ply_path)
print(point_cloud)
points = np.asarray(point_cloud.points)
print(points.shape)
print(points.size)
points = points[np.linalg.norm(points - [0, 0, 0], axis=1) > 1e-6]
print(points.shape)
print(points.size)

PointCloud with 256000 points.
(256000, 3)
768000
(41680, 3)
125040


In [16]:
num_points = points.shape[0]
print(num_points)

41680


In [18]:
padded_points = np.zeros((num_points, 3))
padded_points[:num_points] = points

In [26]:
print(padded_points.shape)
print(padded_points.size)
print(padded_points.ndim)

(41680, 3)
125040
2


In [38]:
ply_path = "./data/pipe_shape_detection2/left/open_0026.ply"  # 将此路径替换为你的文件夹路径
point_cloud = o3d.io.read_point_cloud(ply_path)
print(point_cloud)
points = np.asarray(point_cloud.points)
print(points.shape)
print(points.size)
points = points[np.linalg.norm(points - [0.000000, 0.000000, 0.000000], axis=1) > 1e-1]
print(points.shape)
print(points.size)

[Open3D WARNING] Read PLY failed: unable to open file: ./data/pipe_shape_detection2/left/open_0026.ply
PointCloud with 0 points.
(0, 3)
0
(0, 3)
0


41680
